blueprint:
  name: ðŸŽ® Controller - IKEA BILRESA E2489 Dual Button (Matter Â· Unified)
  author: napalmz
  description: |
    # ðŸŽ® Controller - IKEA BILRESA E2489 Dual Button (Matter Â· Unified)

    Unified controller blueprint for IKEA BILRESA E2489 Matter dual button.
    Supports single & double click, long press/release.
    Emits "uhb_controller_event" for use with my hooks.

    â„¹ï¸ Version 2026.02.24
  domain: automation
  homeassistant:
    min_version: 2025.12.0

  input:
    controller_device:
      name: BILRESA Button Device
      description: >
        Select the IKEA BILRESA E2489 device. This is informational only.
      selector:
        device:
          filter:
            - integration: matter
              manufacturer: IKEA of Sweden
              model: BILRESA dual button
          multiple: false

    button_1_event:
      name: Large Button - Event Entity
      selector:
        entity:
          integration: matter
          domain: event
          multiple: false
          reorder: false

    button_2_event:
      name: Small Button - Event Entity
      selector:
        entity:
          integration: matter
          domain: event
          multiple: false
          reorder: false

    # ---------------------------------------------------------------
    # BUTTON 1 ACTIONS
    # ---------------------------------------------------------------

    button_1_single:
      name: Large Button - Single Press
      description: Action for Large Button single press (multi_press_1).
      default: []
      selector:
        action: {}

    button_1_double:
      name: Large Button - Double Press
      description: Action for Large Button double press (multi_press_2).
      default: []
      selector:
        action: {}

    button_1_long_press:
      name: Large Button - Long Press (while held)
      description: Action for Large Button long_press (mentre premuto).
      default: []
      selector:
        action: {}
    button_1_long_release:
      name: Large Button - Long Press (on release)
      description: Action for Large Button long press completion (long_release).
      default: []
      selector:
        action: {}

    # ---------------------------------------------------------------
    # BUTTON 2 ACTIONS
    # ---------------------------------------------------------------

    button_2_single:
      name: Small Button - Single Press
      description: Action for Small Button single press (multi_press_1).
      default: []
      selector:
        action: {}

    button_2_double:
      name: Small Button - Double Press
      description: Action for Small Button double press (multi_press_2).
      default: []
      selector:
        action: {}

    button_2_long_press:
      name: Small Button - Long Press (while held)
      description: Action for Small Button long_press (mentre premuto).
      default: []
      selector:
        action: {}
    button_2_long_release:
      name: Small Button - Long Press (on release)
      description: Action for Small Button long press completion (long_release).
      default: []
      selector:
        action: {}

variables:
  controller_device: !input controller_device
  controller: "{{ controller_device }}"
  btn1_entity: !input button_1_event
  btn2_entity: !input button_2_event

trigger:
  - platform: state
    id: button1
    entity_id: !input button_1_event
  - platform: state
    id: button2
    entity_id: !input button_2_event

condition: []

action:
  - variables:
      press_type: "{{ trigger.to_state.attributes.event_type }}"
      trigger_id: "{{ trigger.id }}"

  - choose:
      # --- BUTTON 1 ---
      - conditions:
          - condition: template
            value_template: >
              {{ trigger_id == 'button1' and press_type == 'multi_press_1' }}
        sequence:
          - event: uhb_controller_event
            event_data:
              controller: "{{ controller }}"
              button: 1
              action: button_single
          - choose:
              - conditions: []
                sequence: !input button_1_single
      - conditions:
          - condition: template
            value_template: >
              {{ trigger_id == 'button1' and press_type == 'multi_press_2' }}
        sequence:
          - event: uhb_controller_event
            event_data:
              controller: "{{ controller }}"
              button: 1
              action: button_double
          - choose:
              - conditions: []
                sequence: !input button_1_double
      - conditions:
          - condition: template
            value_template: >
              {{ trigger_id == 'button1' and press_type == 'long_press' }}
        sequence:
          - event: uhb_controller_event
            event_data:
              controller: "{{ controller }}"
              button: 1
              action: button_long_press
          - choose:
              - conditions: []
                sequence: !input button_1_long_press
      - conditions:
          - condition: template
            value_template: >
              {{ trigger_id == 'button1' and press_type == 'long_release' }}
        sequence:
          - event: uhb_controller_event
            event_data:
              controller: "{{ controller }}"
              button: 1
              action: button_long_release
          - choose:
              - conditions: []
                sequence: !input button_1_long_release
      # --- BUTTON 2 ---
      - conditions:
          - condition: template
            value_template: >
              {{ trigger_id == 'button2' and press_type == 'multi_press_1' }}
        sequence:
          - event: uhb_controller_event
            event_data:
              controller: "{{ controller }}"
              button: 2
              action: button_single
          - choose:
              - conditions: []
                sequence: !input button_2_single
      - conditions:
          - condition: template
            value_template: >
              {{ trigger_id == 'button2' and press_type == 'multi_press_2' }}
        sequence:
          - event: uhb_controller_event
            event_data:
              controller: "{{ controller }}"
              button: 2
              action: button_double
          - choose:
              - conditions: []
                sequence: !input button_2_double
      - conditions:
          - condition: template
            value_template: >
              {{ trigger_id == 'button2' and press_type == 'long_press' }}
        sequence:
          - event: uhb_controller_event
            event_data:
              controller: "{{ controller }}"
              button: 2
              action: button_long_press
          - choose:
              - conditions: []
                sequence: !input button_2_long_press
      - conditions:
          - condition: template
            value_template: >
              {{ trigger_id == 'button2' and press_type == 'long_release' }}
        sequence:
          - event: uhb_controller_event
            event_data:
              controller: "{{ controller }}"
              button: 2
              action: button_long_release
          - choose:
              - conditions: []
                sequence: !input button_2_long_release

mode: restart