blueprint:
  name: ðŸŽ® Controller - IKEA BILRESA E2490 Scroll Wheel (Matter Â· Unified)
  author: napalmz
  description: |
    # ðŸŽ® Controller - IKEA BILRESA E2490 Scroll Wheel (Matter Â· Unified)

    Unified controller blueprint for IKEA BILRESA E2490 Matter scroll wheel.
    Supports channel 1/2/3, single & double click, long press/release,
    and wheel rotation with step count.
    Emits "uhb_controller_event" for use with my hooks.

    â„¹ï¸ Version 2026.02.24
  domain: automation
  homeassistant:
    min_version: 2025.12.0

  input:
    controller_device:
      name: BILRESA Scroll Wheel Device
      description: >
        Select the IKEA BILRESA E2490 device. This is informational only.
      selector:
        device:
          filter:
            - integration: matter
              manufacturer: IKEA of Sweden
              model: BILRESA scroll wheel
          multiple: false

    channel:
      name: Active Channel
      description: Select which channel (1 / 2 / 3) this automation represents.
      default: "1"
      selector:
        select:
          options:
            - "1"
            - "2"
            - "3"

    press_event:
      name: Pressed - Event entity (selected channel)
      selector:
        entity:
          integration: matter
          domain: event
          multiple: false
          reorder: false

    rotate_forward_event:
      name: Scroll forward - Event entity (selected channel)
      selector:
        entity:
          integration: matter
          domain: event
          multiple: false
          reorder: false

    rotate_backward_event:
      name: Scroll back - Event entity (selected channel)
      selector:
        entity:
          integration: matter
          domain: event
          multiple: false
          reorder: false

    # ---------------------------------------------------------------
    # ACTIONS (all optional)
    # ---------------------------------------------------------------
    action_button_single:
      name: Button Single Press
      description: Action for single press (multi_press_1)
      default: []
      selector:
        action: {}
    action_button_double:
      name: Button Double Press
      description: Action for double press (multi_press_2)
      default: []
      selector:
        action: {}
    action_button_triple:
      name: Button Triple Press
      description: Action for triple press (multi_press_3)
      default: []
      selector:
        action: {}
    action_button_long:
      name: Button Long Press
      description: Action for long press (long_press)
      default: []
      selector:
        action: {}
    action_button_release:
      name: Button Long Release
      description: Action for long release (long_release)
      default: []
      selector:
        action: {}
    action_rotate_up:
      name: Rotate Forward
      description: Action for scroll forward (rotate_up)
      default: []
      selector:
        action: {}
    action_rotate_down:
      name: Rotate Backward
      description: Action for scroll backward (rotate_down)
      default: []
      selector:
        action: {}

variables:
  controller_device: !input controller_device
  controller: "{{ controller_device }}"
  channel: !input channel
  press_entity: !input press_event
  fwd_entity: !input rotate_forward_event
  back_entity: !input rotate_backward_event

trigger:
  - platform: state
    entity_id:
      - !input press_event
      - !input rotate_forward_event
      - !input rotate_backward_event

condition: []

action:
  - variables:
      entity: "{{ trigger.entity_id }}"
      event_type: "{{ trigger.to_state.attributes.event_type }}"
      steps: "{{ trigger.to_state.attributes.totalNumberOfPressesCounted | int(1) }}"

  - choose:

      # -------------------------------------------------
      # CLICK / PRESS
      # -------------------------------------------------
      - conditions: >
          {{ entity == press_entity and event_type == 'multi_press_1' }}
        sequence:
          - event: uhb_controller_event
            event_data:
              controller: "{{ controller }}"
              channel: "{{ channel }}"
              action: button_single
          - choose:
              - conditions: []
                sequence: !input action_button_single

      - conditions: >
          {{ entity == press_entity and event_type == 'multi_press_2' }}
        sequence:
          - event: uhb_controller_event
            event_data:
              controller: "{{ controller }}"
              channel: "{{ channel }}"
              action: button_double
          - choose:
              - conditions: []
                sequence: !input action_button_double

      - conditions: >
          {{ entity == press_entity and event_type == 'multi_press_3' }}
        sequence:
          - event: uhb_controller_event
            event_data:
              controller: "{{ controller }}"
              channel: "{{ channel }}"
              action: button_triple
          - choose:
              - conditions: []
                sequence: !input action_button_triple

      - conditions: >
          {{ entity == press_entity and event_type == 'long_press' }}
        sequence:
          - event: uhb_controller_event
            event_data:
              controller: "{{ controller }}"
              channel: "{{ channel }}"
              action: button_long
          - choose:
              - conditions: []
                sequence: !input action_button_long

      - conditions: >
          {{ entity == press_entity and event_type == 'long_release' }}
        sequence:
          - event: uhb_controller_event
            event_data:
              controller: "{{ controller }}"
              channel: "{{ channel }}"
              action: button_release
          - choose:
              - conditions: []
                sequence: !input action_button_release

      - conditions: "{{ entity == fwd_entity }}"
        sequence:
          - event: uhb_controller_event
            event_data:
              controller: "{{ controller }}"
              channel: "{{ channel }}"
              action: rotate_up
              args:
                steps: "{{ steps }}"
          - choose:
              - conditions: []
                sequence: !input action_rotate_up

      - conditions: "{{ entity == back_entity }}"
        sequence:
          - event: uhb_controller_event
            event_data:
              controller: "{{ controller }}"
              channel: "{{ channel }}"
              action: rotate_down
              args:
                steps: "{{ steps }}"
          - choose:
              - conditions: []
                sequence: !input action_rotate_down

mode: restart
