blueprint:
  name: 🪝 Hook - UHB Controller Light (Matter · Unified)
  author: napalmz
  description: |
    # 🪝 Hook - UHB Controller Light (Matter · Unified)

    Gestione avanzata per luci tramite eventi custom `uhb_controller_event` dei controller IKEA E2489 (2 pulsanti) ed E2490 (pulsante+rotella).
    La logica delle azioni si adatta automaticamente al tipo di controller:
    - E2489: pulsante 1 accende/aumenta, pulsante 2 spegne/diminuisce
    - E2490: pressione = toggle, rotazione = regola luminosità, long press = accendi al minimo

    ℹ️ Version 2026.02.25
  domain: automation
  homeassistant:
    min_version: 2025.12.0

  input:
    controller_model:
      name: Modello controller
      description: Seleziona il modello di controller usato
      selector:
        select:
          options:
            - IKEA BILRESA E2489 Dual Button
            - IKEA BILRESA E2490 Scroll Wheel
    controller_device:
      name: Controller Device
      description: Seleziona il dispositivo controller (deve essere lo stesso usato nel blueprint controller)
      selector:
        device:
          filter:
            - integration: matter
              manufacturer: IKEA of Sweden
              model: BILRESA dual button
            - integration: matter
              manufacturer: IKEA of Sweden
              model: BILRESA scroll wheel
          multiple: false
    macro:
      name: Macro (opzionale, solo E2490)
      description: Seleziona la macro (se usata dal controller, es. E2490). Lascia vuoto per ignorare.
      default: ''
      selector:
        select:
          options:
            - "1"
            - "2"
            - "3"
    light:
      name: Luce da controllare
      description: Seleziona la luce da controllare
      selector:
        entity:
          domain: light
    light_color_mode:
      name: Modalità colore luce (opzionale)
      description: Specifica come il controller imposta il colore della luce. Se non sei sicuro, seleziona "Auto".
      default: Auto
      selector:
        select:
          options:
            - Auto
            - Color Temperature
            - Hue - Saturation
            - None
    light_transition:
      name: Transizione luce (ms)
      description: Tempo in millisecondi per la transizione on/off (se supportata).
      default: 250
      selector:
        number:
          min: 0
          max: 60000
          step: 1
          unit_of_measurement: milliseconds
          mode: box
    min_brightness:
      name: Luminosità minima (opzionale)
      description: Luminosità minima impostabile.
      default: 1
      selector:
        number:
          min: 1
          max: 255
          step: 1
          unit_of_measurement: brightness
          mode: slider
    max_brightness:
      name: Luminosità massima (opzionale)
      description: Luminosità massima impostabile.
      default: 255
      selector:
        number:
          min: 0
          max: 255
          step: 1
          unit_of_measurement: brightness
          mode: slider
    brightness_steps_short:
      name: Step luminosità - azioni brevi
      description: Numero di step da min a max luminosità per azioni brevi (es. pressione).
      default: 10
      selector:
        number:
          min: 1
          max: 255
          step: 1
          unit_of_measurement: steps
          mode: box
    brightness_steps_long:
      name: Step luminosità - azioni lunghe
      description: Numero di step da min a max luminosità per azioni lunghe (es. hold/rotazione).
      default: 10
      selector:
        number:
          min: 1
          max: 255
          step: 1
          unit_of_measurement: steps
          mode: box
    force_brightness:
      name: Forza luminosità all'accensione
      description: Forza la luminosità al valore "On brightness" quando la luce viene accesa.
      default: false
      selector:
        boolean:
    on_brightness:
      name: Luminosità all'accensione
      description: Valore di luminosità da forzare all'accensione.
      default: 1
      selector:
        number:
          min: 0
          max: 255
          step: 1
          unit_of_measurement: brightness
          mode: slider
    smooth_power_on:
      name: Accensione soft (minima luminosità)
      description: Accendi la luce al minimo quando si aumenta la luminosità da off.
      default: true
      selector:
        boolean:
    smooth_power_off:
      name: Spegnimento soft (da minimo)
      description: Permetti di spegnere la luce quando si abbassa la luminosità al minimo.
      default: true
      selector:
        boolean:

mode: restart

trigger:
  - platform: event
    event_type: uhb_controller_event
    event_data:
      controller: !input controller_device

variables:
  action_type: "{{ trigger.event.data.action }}"
  button: "{{ trigger.event.data.button | default(1) }}"
  macro: "{{ trigger.event.data.macro | default('') }}"
  macro_filter: !input macro
  light: !input light
  light_color_mode: !input light_color_mode
  light_transition: !input light_transition
  min_brightness: !input min_brightness
  max_brightness: !input max_brightness
  brightness_steps_short: !input brightness_steps_short
  brightness_steps_long: !input brightness_steps_long
  force_brightness: !input force_brightness
  on_brightness: !input on_brightness
  smooth_power_on: !input smooth_power_on
  smooth_power_off: !input smooth_power_off
  step_short: "{{ ((max_brightness-min_brightness)//brightness_steps_short) | int }}"
  step_long: "{{ ((max_brightness-min_brightness)//brightness_steps_long) | int }}"
  controller_model: !input controller_model
  controller_device: !input controller_device

condition:
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ macro_filter == '' }}"
      - condition: template
        value_template: "{{ macro_filter == macro }}"

action:
  - choose:
      # --- E2489: Pulsante 1 (accendi/aumenta) ---
      - conditions: "{{ controller_model == 'IKEA BILRESA E2489 Dual Button' and button == 1 and action_type == 'button_single' }}"
        sequence:
          - choose:
              - conditions: "{{ states(light) == 'off' and smooth_power_on }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ light }}"
                    data:
                      brightness: "{{ min_brightness }}"
                      transition: "{{ light_transition / 1000 }}"
              - conditions: "{{ states(light) == 'off' and not smooth_power_on }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ light }}"
                    data:
                      transition: "{{ light_transition / 1000 }}"
              - conditions: "{{ states(light) == 'on' and force_brightness }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ light }}"
                    data:
                      brightness: "{{ on_brightness }}"
                      transition: "{{ light_transition / 1000 }}"
              - conditions: "{{ states(light) == 'on' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ light }}"
                    data:
                      brightness: "{{ ([ (state_attr(light,'brightness')|int(0) + (step_short|int)), min_brightness|int ] | max, max_brightness|int ) | min }}"
                      transition: "{{ light_transition / 1000 }}"
      - conditions: "{{ controller_model == 'IKEA BILRESA E2489 Dual Button' and button == 1 and action_type in ['button_long', 'long_press'] }}"
        sequence:
          - repeat:
              while: "{{ is_state(light, 'on') and state_attr(light, 'brightness') < max_brightness }}"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ light }}"
                  data:
                    brightness: "{{ ([ (state_attr(light,'brightness')|int(0) + (step_long|int)), min_brightness|int ] | max, max_brightness|int ) | min }}"
                    transition: "{{ light_transition / 1000 }}"
                - delay: 0.25
      # --- E2489: Pulsante 2 (spegni/diminuisci) ---
      - conditions: "{{ controller_model == 'IKEA BILRESA E2489 Dual Button' and button == 2 and action_type == 'button_single' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ light }}"
            data:
              transition: "{{ light_transition / 1000 }}"
      - conditions: "{{ controller_model == 'IKEA BILRESA E2489 Dual Button' and button == 2 and action_type in ['button_long', 'long_press'] }}"
        sequence:
          - repeat:
              while: "{{ is_state(light, 'on') and state_attr(light, 'brightness') > min_brightness }}"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ light }}"
                  data:
                    brightness: "{{ ([ (state_attr(light,'brightness')|int(0) - (step_long|int)), min_brightness|int ] | max, max_brightness|int ) | min }}"
                    transition: "{{ light_transition / 1000 }}"
                - delay: 0.25
          - choose:
              - conditions: "{{ is_state(light, 'on') and smooth_power_off and (state_attr(light, 'brightness') | int(0)) <= min_brightness }}"
                sequence:
                  - service: light.turn_off
                    target:
                      entity_id: "{{ light }}"
                    data:
                      transition: "{{ light_transition / 1000 }}"
      # --- E2490: Pulsante/Rotella ---
      - conditions: "{{ controller_model == 'IKEA BILRESA E2490 Scroll Wheel' and action_type == 'button_single' }}"
        sequence:
          - choose:
              - conditions: "{{ force_brightness }}"
                sequence:
                  - service: light.toggle
                    target:
                      entity_id: "{{ light }}"
                    data:
                      brightness: "{{ on_brightness }}"
                      transition: "{{ light_transition / 1000 }}"
              - conditions: "{{ not force_brightness }}"
                sequence:
                  - service: light.toggle
                    target:
                      entity_id: "{{ light }}"
                    data:
                      transition: "{{ light_transition / 1000 }}"
      - conditions: "{{ controller_model == 'IKEA BILRESA E2490 Scroll Wheel' and action_type == 'long_press' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light }}"
            data:
              brightness: "{{ min_brightness }}"
              transition: "{{ light_transition / 1000 }}"
      - conditions: "{{ controller_model == 'IKEA BILRESA E2490 Scroll Wheel' and action_type == 'rotate_up' }}"
        sequence:
          - choose:
              - conditions: "{{ states(light) == 'off' and smooth_power_on }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ light }}"
                    data:
                      brightness: "{{ min_brightness }}"
                      transition: "{{ light_transition / 1000 }}"
              - conditions: "{{ states(light) == 'off' and not smooth_power_on }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ light }}"
                    data:
                      transition: "{{ light_transition / 1000 }}"
              - conditions: "{{ states(light) == 'on' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ light }}"
                    data:
                      brightness: "{{ [ [state_attr(light,'brightness')+step_short, min_brightness] | max, max_brightness ] | min }}"
                      transition: "{{ light_transition / 1000 }}"
      - conditions: "{{ controller_model == 'IKEA BILRESA E2490 Scroll Wheel' and action_type == 'rotate_down' and states(light) == 'on' }}"
        sequence:
          - choose:
              - conditions: "{{ smooth_power_off and state_attr(light,'brightness') == min_brightness }}"
                sequence:
                  - service: light.turn_off
                    target:
                      entity_id: "{{ light }}"
                    data:
                      transition: "{{ light_transition / 1000 }}"
              - conditions: "{{ state_attr(light,'brightness') > min_brightness }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ light }}"
                    data:
                      brightness: "{{ ([ (state_attr(light,'brightness')|int(0) - (step_short|int)), min_brightness|int ] | max, max_brightness|int ) | min }}"
                      transition: "{{ light_transition / 1000 }}"